---
title: "Canada"
---
# National Instrument 43-101

The 43-101 is a national instrument for the Standards of Disclosure for Mineral Projects within Canada. The Instrument is a codified set of rules and guidelines for reporting and displaying information related to mineral properties owned by, or explored by, companies which report these results on stock exchanges within Canada. This includes foreign-owned mining entities who trade on stock exchanges overseen by the Canadian Securities Administrators, even if they only trade on Over The Counter (OTC) derivatives or other instrumented securities.

The purpose of National Instrument 43-101 is to ensure that misleading, erroneous or fraudulent information relating to mineral properties is not published and promoted to investors on the stock exchanges overseen by the Canadian Securities Authority. The NI 43-101 was created after the Bre-X scandal to protect investors from unsubstantiated mineral project disclosures.

Disclosures covered by the NI 43-101 code include press releases of mineral exploration reports, reporting of resources and reserves, presentations, oral comments, and websites. The NI 43-101 covers metalliferous, precious metals and solid energy commodities as well as bulk minerals, dimension stone, precious stones and mineral sands commodities.

43-101 is broadly comparable to the Joint Ore Reserves Committee Code (JORC Code) which regulates the publication of mineral exploration reports on the Australian Stock Exchange (ASX). It is also broadly comparable with the South African Code for the Reporting of Mineral Resources and Mineral Reserves (SAMREC).